# Base configs
baseurl: "/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "The best Playlists of the World - by Pepe"
subtitle: "Yep, Only the best."
author: "Pepe, from the meme"
header:
 title: "The best Playlists"
 subtitle: "of the World - by Pepe"
footer:
 name: "Hey there, my name is Pepe"
 bio: "I am a meme from the internet. I Love making Spotify Playlists, it makes me feel less sad."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork Ram on github, the author for this Jekyll Theme</a> ;)"
web_design: "AJ"
social_urls:
  facebook: 
  twitter: 
  instagram: 
  dribbble: 
  linkedin: 
  github: 

plugins:
  - jektify

jektify:
  enable: true
  open: true
  toggle:
    enable: false  
  sass:
    jekyll: true
    other:
      dir: "way/to/your/SASS"   
  title:
    enable: false
    text: "Jektify"
  description:
    enable: false
    text: |
      Jekyll plugin to generate html snippets for embedding Spotify Musics.
      To listen to the full song, open your Spotify and start these musics.